#!/bin/bash

set -e

VENDOR_ODM_PATH=$(readlink -f $1)
VENDOR_PROP_FILE=proprietary-files-vendor.txt
VENDOR_SYMLINKS_MK=vendor-symlinks.mk

VENDOR_SKIP_FILES=(
    # Apps DEX
    "*/app/CACertService/oat/arm64/CACertService.odex"
    "*/app/CACertService/oat/arm64/CACertService.vdex"
    "*/app/CneApp/oat/arm64/CneApp.odex"
    "*/app/CneApp/oat/arm64/CneApp.vdex"
    "*/app/EidService/oat/arm64/EidService.odex"
    "*/app/EidService/oat/arm64/EidService.vdex"
    "*/app/goodix_sz/oat/arm64/goodix_sz.odex"
    "*/app/goodix_sz/oat/arm64/goodix_sz.vdex"
    "*/app/IWlanService/oat/arm64/IWlanService.odex"
    "*/app/IWlanService/oat/arm64/IWlanService.vdex"
    "*/app/QFingerprintService/oat/arm64/QFingerprintService.odex"
    "*/app/QFingerprintService/oat/arm64/QFingerprintService.vdex"
    "*/app/TimeService/oat/arm64/TimeService.odex"
    "*/app/TimeService/oat/arm64/TimeService.vdex"
    "*/app/TrustedUIService/oat/arm64/TrustedUIService.odex"
    "*/app/TrustedUIService/oat/arm64/TrustedUIService.vdex"
    "*/app/TrustZoneAccessService/oat/arm64/TrustZoneAccessService.odex"
    "*/app/TrustZoneAccessService/oat/arm64/TrustZoneAccessService.vdex"
    "*/framework/oat/arm64/androidx.camera.extensions.impl.odex"
    "*/framework/oat/arm64/androidx.camera.extensions.impl.vdex"
    "*/framework/oat/arm/androidx.camera.extensions.impl.odex"
    "*/framework/oat/arm/androidx.camera.extensions.impl.vdex"

    # Audio
    "*/bin/agmcap"
    "*/bin/agmcompresscap"
    "*/bin/agmcompressplay"
    "*/bin/agmhostless"
    "*/bin/agmplay"
    "*/bin/agmvoiceui"
    "*/bin/audioadsprpcd"
    "*/bin/PalTest"
    "*/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd"
    "*/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd"
    "*/etc/init/android.hardware.audio.service_64.rc"
    "*/etc/init/vendor.qti.audio-adsprpc-service.rc"
    "*/etc/vintf/manifest/manifest_non_qmaa_extn.xml"
    "*/etc/vintf/manifest/manifest_non_qmaa.xml"
    "*/lib64/android.hardware.audio@2.0.so"
    "*/lib64/android.hardware.audio@2.0-util.so"
    "*/lib64/android.hardware.audio@4.0.so"
    "*/lib64/android.hardware.audio@4.0-util.so"
    "*/lib64/android.hardware.audio@5.0.so"
    "*/lib64/android.hardware.audio@5.0-util.so"
    "*/lib64/android.hardware.audio@6.0.so"
    "*/lib64/android.hardware.audio@6.0-util.so"
    "*/lib64/android.hardware.audio@7.0.so"
    "*/lib64/android.hardware.audio@7.0-util.so"
    "*/lib64/android.hardware.audio@7.1.so"
    "*/lib64/android.hardware.audio@7.1-util.so"
    "*/lib64/android.hardware.audio.common@2.0-util.so"
    "*/lib64/android.hardware.audio.common@4.0.so"
    "*/lib64/android.hardware.audio.common@4.0-util.so"
    "*/lib64/android.hardware.audio.common@5.0.so"
    "*/lib64/android.hardware.audio.common@5.0-util.so"
    "*/lib64/android.hardware.audio.common@6.0.so"
    "*/lib64/android.hardware.audio.common@6.0-util.so"
    "*/lib64/android.hardware.audio.common@7.0-enums.so"
    "*/lib64/android.hardware.audio.common@7.0.so"
    "*/lib64/android.hardware.audio.common@7.0-util.so"
    "*/lib64/android.hardware.audio.common@7.1-enums.so"
    "*/lib64/android.hardware.audio.common@7.1-util.so"
    "*/lib64/android.hardware.audio.common-util.so"
    "*/lib64/android.hardware.audio.effect@2.0.so"
    "*/lib64/android.hardware.audio.effect@2.0-util.so"
    "*/lib64/android.hardware.audio.effect@4.0.so"
    "*/lib64/android.hardware.audio.effect@4.0-util.so"
    "*/lib64/android.hardware.audio.effect@5.0.so"
    "*/lib64/android.hardware.audio.effect@5.0-util.so"
    "*/lib64/android.hardware.audio.effect@6.0.so"
    "*/lib64/android.hardware.audio.effect@6.0-util.so"
    "*/lib64/android.hardware.audio.effect@7.0.so"
    "*/lib64/android.hardware.audio.effect@7.0-util.so"
    "*/lib64/android.hardware.soundtrigger@2.1.so"
    "*/lib64/android.hardware.soundtrigger@2.2.so"
    "*/lib64/android.hardware.soundtrigger@2.3.so"
    "*/lib64/hw/android.hardware.audio@2.0-impl.so"
    "*/lib64/hw/android.hardware.audio@4.0-impl.so"
    "*/lib64/hw/android.hardware.audio@5.0-impl.so"
    "*/lib64/hw/android.hardware.audio@6.0-impl.so"
    "*/lib64/hw/android.hardware.audio@7.0-impl.so"
    "*/lib64/hw/android.hardware.audio@7.1-impl.so"
    "*/lib64/hw/android.hardware.audio.effect@2.0-impl.so"
    "*/lib64/hw/android.hardware.audio.effect@4.0-impl.so"
    "*/lib64/hw/android.hardware.audio.effect@5.0-impl.so"
    "*/lib64/hw/android.hardware.audio.effect@6.0-impl.so"
    "*/lib64/hw/android.hardware.audio.effect@7.0-impl.so"
    "*/lib64/hw/android.hardware.soundtrigger@2.2-impl.so"
    "*/lib64/hw/android.hardware.soundtrigger@2.3-impl.so"
    "*/lib64/hw/audio.primary.default.so"
    "*/lib64/hw/audio.r_submix.default.so"
    "*/lib64/hw/sound_trigger.primary.kalama.so"
    "*/lib64/libagmclient.so"
    "*/lib64/libagm_compress_plugin.so"
    "*/lib64/libagm_mixer_plugin.so"
    "*/lib64/libagmmixer.so"
    "*/lib64/libagm_pcm_plugin.so"
    "*/lib64/libalsautils.so"
    "*/lib64/libaudiochargerlistener.so"
    "*/lib64/libbatterylistener.so"
    "*/lib64/libfmpal.so"
    "*/lib64/libhfp_pal.so"
    "*/lib64/libmemunreachable.so"
    "*/lib64/libnbaio_mono.so"
    "*/lib64/liboffloadhal.so"
    "*/lib64/libpalclient.so"
    "*/lib64/libsndcardparser.so"
    "*/lib64/libtinycompress.so"
    "*/lib64/soundfx/libaudiopreprocessing.so"
    "*/lib64/soundfx/libbundlewrapper.so"
    "*/lib64/soundfx/libdownmix.so"
    "*/lib64/soundfx/libdynproc.so"
    "*/lib64/soundfx/libeffectproxy.so"
    "*/lib64/soundfx/libhapticgenerator.so"
    "*/lib64/soundfx/libldnhncr.so"
    "*/lib64/soundfx/libqcompostprocbundle.so"
    "*/lib64/soundfx/libqcomvisualizer.so"
    "*/lib64/soundfx/libqcomvoiceprocessing.so"
    "*/lib64/soundfx/libreverbwrapper.so"
    "*/lib64/soundfx/libvisualizer.so"
    "*/lib64/soundfx/libvolumelistener.so"
    "*/lib64/vendor.qti.hardware.AGMIPC@1.0.so"
    "*/lib64/vendor.qti.hardware.pal@1.0.so"
    "*/lib/android.hardware.audio@2.0.so"
    "*/lib/android.hardware.audio@2.0-util.so"
    "*/lib/android.hardware.audio@4.0.so"
    "*/lib/android.hardware.audio@4.0-util.so"
    "*/lib/android.hardware.audio@5.0.so"
    "*/lib/android.hardware.audio@5.0-util.so"
    "*/lib/android.hardware.audio@6.0.so"
    "*/lib/android.hardware.audio@6.0-util.so"
    "*/lib/android.hardware.audio@7.0.so"
    "*/lib/android.hardware.audio@7.0-util.so"
    "*/lib/android.hardware.audio@7.1.so"
    "*/lib/android.hardware.audio@7.1-util.so"
    "*/lib/android.hardware.audio.common@2.0-util.so"
    "*/lib/android.hardware.audio.common@4.0.so"
    "*/lib/android.hardware.audio.common@4.0-util.so"
    "*/lib/android.hardware.audio.common@5.0.so"
    "*/lib/android.hardware.audio.common@5.0-util.so"
    "*/lib/android.hardware.audio.common@6.0.so"
    "*/lib/android.hardware.audio.common@6.0-util.so"
    "*/lib/android.hardware.audio.common@7.0-enums.so"
    "*/lib/android.hardware.audio.common@7.0.so"
    "*/lib/android.hardware.audio.common@7.0-util.so"
    "*/lib/android.hardware.audio.common@7.1-enums.so"
    "*/lib/android.hardware.audio.common@7.1-util.so"
    "*/lib/android.hardware.audio.common-util.so"
    "*/lib/android.hardware.audio.effect@2.0.so"
    "*/lib/android.hardware.audio.effect@2.0-util.so"
    "*/lib/android.hardware.audio.effect@4.0.so"
    "*/lib/android.hardware.audio.effect@4.0-util.so"
    "*/lib/android.hardware.audio.effect@5.0.so"
    "*/lib/android.hardware.audio.effect@5.0-util.so"
    "*/lib/android.hardware.audio.effect@6.0.so"
    "*/lib/android.hardware.audio.effect@6.0-util.so"
    "*/lib/android.hardware.audio.effect@7.0.so"
    "*/lib/android.hardware.audio.effect@7.0-util.so"
    "*/lib/android.hardware.soundtrigger@2.1.so"
    "*/lib/android.hardware.soundtrigger@2.2.so"
    "*/lib/android.hardware.soundtrigger@2.3.so"
    "*/lib/hw/android.hardware.audio@2.0-impl.so"
    "*/lib/hw/android.hardware.audio@4.0-impl.so"
    "*/lib/hw/android.hardware.audio@5.0-impl.so"
    "*/lib/hw/android.hardware.audio@6.0-impl.so"
    "*/lib/hw/android.hardware.audio@7.0-impl.so"
    "*/lib/hw/android.hardware.audio@7.1-impl.so"
    "*/lib/hw/android.hardware.audio.effect@2.0-impl.so"
    "*/lib/hw/android.hardware.audio.effect@4.0-impl.so"
    "*/lib/hw/android.hardware.audio.effect@5.0-impl.so"
    "*/lib/hw/android.hardware.audio.effect@6.0-impl.so"
    "*/lib/hw/android.hardware.audio.effect@7.0-impl.so"
    "*/lib/hw/android.hardware.soundtrigger@2.1-impl.so"
    "*/lib/hw/android.hardware.soundtrigger@2.2-impl.so"
    "*/lib/hw/android.hardware.soundtrigger@2.3-impl.so"
    "*/lib/hw/audio.primary.default.so"
    "*/lib/hw/audio.r_submix.default.so"
    "*/lib/hw/sound_trigger.primary.kalama.so"
    "*/lib/libagmclient.so"
    "*/lib/libagm_compress_plugin.so"
    "*/lib/libagm_mixer_plugin.so"
    "*/lib/libagmmixer.so"
    "*/lib/libagm_pcm_plugin.so"
    "*/lib/libalsautils.so"
    "*/lib/libaudiochargerlistener.so"
    "*/lib/libbatterylistener.so"
    "*/lib/libfmpal.so"
    "*/lib/libhfp_pal.so"
    "*/lib/libmemunreachable.so"
    "*/lib/libnbaio_mono.so"
    "*/lib/libpalclient.so"
    "*/lib/libsndcardparser.so"
    "*/lib/libtinycompress.so"
    "*/lib/soundfx/libaudiopreprocessing.so"
    "*/lib/soundfx/libbundlewrapper.so"
    "*/lib/soundfx/libdownmix.so"
    "*/lib/soundfx/libdynproc.so"
    "*/lib/soundfx/libeffectproxy.so"
    "*/lib/soundfx/libhapticgenerator.so"
    "*/lib/soundfx/libldnhncr.so"
    "*/lib/soundfx/libqcompostprocbundle.so"
    "*/lib/soundfx/libqcomvisualizer.so"
    "*/lib/soundfx/libqcomvoiceprocessing.so"
    "*/lib/soundfx/libreverbwrapper.so"
    "*/lib/soundfx/libvisualizer.so"
    "*/lib/soundfx/libvolumelistener.so"
    "*/lib/vendor.qti.hardware.AGMIPC@1.0.so"
    "*/lib/vendor.qti.hardware.pal@1.0.so"

    # Automotive
    "*/lib64/android.automotive.watchdog-V2-ndk.so"
    "*/lib64/android.hardware.automotive.vehicle@2.0-manager-lib.so"
    "*/lib64/android.hardware.automotive.vehicle@2.0.so"
    "*/lib/android.automotive.watchdog-V2-ndk.so"
    "*/lib/android.hardware.automotive.vehicle@2.0-manager-lib.so"
    "*/lib/android.hardware.automotive.vehicle@2.0.so"

    # ADSP
    "*/lib/rfsa/adsp/libvpt_action_recognition.so"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n29.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n30.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n35.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n36.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n37.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n38.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n39.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n40.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n46.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n47.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n48.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n49.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n52.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a68v08s11n53.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n02.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n03.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n04.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n06.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n07.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n08.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n09.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n12.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n13.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n14.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n15.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n16.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n17.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n18.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n19.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n20.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n21.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n22.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n23.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n24.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n25.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n26.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n27.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n28.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n41.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n42.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n43.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n44.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n45.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n50.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n51.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n57.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n58.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n59.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n60.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n61.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n62.bin"
    "*/mount/camera/lib/rfsa/adsp/bm3a73v08s11n63.bin"

    # ANT
    "*/lib64/com.dsi.ant@1.0.so"
    "*/lib/com.dsi.ant@1.0.so"

    # Atrace
    "*/bin/hw/android.hardware.atrace@1.0-service"
    "*/etc/init/android.hardware.atrace@1.0-service.rc"
    "*/etc/vintf/manifest/android.hardware.atrace@1.0-service.xml"
    "*/lib64/android.hardware.atrace@1.0.so"

    # AuthSecret
    "*/lib64/android.hardware.authsecret@1.0.so"
    "*/lib/android.hardware.authsecret@1.0.so"

    # Biometrics
    "*/bin/hw/android.hardware.biometrics.face-aidl-service"
    "*/bin/mifaced@1.0"
    "*/etc/init/android.hardware.biometrics.face-aidl-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.miface@1.0-service.rc"
    "*/etc/permissions/android.hardware.biometrics.face.xml"
    "*/etc/vintf/manifest/face-default.xml"
    "*/etc/vintf/manifest/manifest_vendor.xiaomi.hardware.miface.xml"
    "*/lib64/android.hardware.biometrics.common-V2-ndk.so"
    "*/lib64/android.hardware.biometrics.face-V2-ndk.so"
    "*/lib64/android.hardware.biometrics.fingerprint@2.1.so"
    "*/lib64/libmiface.so"
    "*/lib64/vendor.xiaomi.hardware.miface@1.0.so"
    "*/lib/libmiface.so"
    "*/lib/vendor.xiaomi.hardware.miface@1.0.so"

    # Bluetooth
    "*/bin/btconfig"
    "*/lib64/android.hardware.bluetooth@1.0.so"
    "*/lib64/android.hardware.bluetooth@1.1.so"
    "*/lib64/android.hardware.bluetooth.audio@2.0.so"
    "*/lib64/android.hardware.bluetooth.audio@2.1.so"
    "*/lib64/hw/android.hardware.bluetooth.audio@2.0-impl.so"
    "*/lib64/hw/audio.bluetooth.default.so"
    "*/lib64/libbluetooth_audio_session_aidl.so"
    "*/lib64/libbluetooth_audio_session.so"
    "*/lib64/vendor.qti.hardware.bluetooth_audio@2.0.so"
    "*/lib64/vendor.qti.hardware.bluetooth_audio@2.1.so"
    "*/lib64/vendor.qti.hardware.bluetooth.audio-V1-ndk.so"
    "*/lib64/vendor.qti.hardware.btconfigstore@1.0.so"
    "*/lib64/vendor.qti.hardware.btconfigstore@2.0.so"
    "*/lib/android.hardware.bluetooth@1.0.so"
    "*/lib/android.hardware.bluetooth@1.1.so"
    "*/lib/android.hardware.bluetooth.audio@2.0.so"
    "*/lib/android.hardware.bluetooth.audio@2.1.so"
    "*/lib/hw/android.hardware.bluetooth.audio@2.0-impl.so"
    "*/lib/hw/audio.bluetooth.default.so"
    "*/lib/libbluetooth_audio_session_aidl.so"
    "*/lib/libbluetooth_audio_session.so"
    "*/lib/vendor.qti.hardware.bluetooth_audio@2.0.so"
    "*/lib/vendor.qti.hardware.bluetooth_audio@2.1.so"
    "*/lib/vendor.qti.hardware.bluetooth.audio-V1-ndk.so"
    "*/lib/vendor.qti.hardware.btconfigstore@1.0.so"
    "*/lib/vendor.qti.hardware.btconfigstore@2.0.so"

    # Boot control
    "*/bin/hw/android.hardware.boot@1.2-service"
    "*/etc/init/android.hardware.boot@1.2-service.rc"
    "*/etc/vintf/manifest/android.hardware.boot@1.2.xml"
    "*/lib64/android.hardware.boot@1.0.so"
    "*/lib64/android.hardware.boot@1.1.so"
    "*/lib64/android.hardware.boot@1.2.so"
    "*/lib64/hw/android.hardware.boot@1.0-impl-1.2-qti.so"
    "*/lib64/libboot_control_qti.so"
    "*/lib/android.hardware.boot@1.0.so"
    "*/lib/android.hardware.boot@1.1.so"
    "*/lib/android.hardware.boot@1.2.so"
    "*/lib/hw/android.hardware.boot@1.0-impl-1.2-qti.so"
    "*/lib/libboot_control_qti.so"

    # BoringSSL
    "*/bin/boringssl_self_test32"
    "*/bin/boringssl_self_test64"
    "*/etc/init/boringssl_self_test.rc"

    # Build properties
    "*/build.prop"
    "*/etc/build.prop"
    "*/odm_dlkm/etc/build.prop"

    # CapabilityConfigstore
    "*/lib64/vendor.qti.hardware.capabilityconfigstore@1.0.so"
    "*/lib/vendor.qti.hardware.capabilityconfigstore@1.0.so"

    # Camera plugins
    "*/lib64/camera/plugins/com.xiaomi.plugin.deflicker.so"
    "*/lib64/camera/plugins/com.xiaomi.plugin.frontbokeh.so"
    "*/lib64/camera/plugins/com.xiaomi.plugin.miaiie.so"
    "*/lib64/camera/plugins/com.xiaomi.plugin.supermoon.so"

    # Camera
    "*/bin/hw/android.hardware.camera.provider@2.7-virtual-camera-service"
    "*/etc/init/android.hardware.camera.provider@2.7-virtual-camera-service.rc"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.vcamera.provider.xml"
    "*/lib64/android.frameworks.cameraservice.common@2.0.so"
    "*/lib64/android.frameworks.cameraservice.device@2.0.so"
    "*/lib64/android.frameworks.cameraservice.device@2.1.so"
    "*/lib64/android.frameworks.cameraservice.service@2.0.so"
    "*/lib64/android.frameworks.cameraservice.service@2.1.so"
    "*/lib64/android.frameworks.cameraservice.service@2.2.so"
    "*/lib64/android.hardware.camera.common@1.0.so"
    "*/lib64/android.hardware.camera.device@1.0.so"
    "*/lib64/android.hardware.camera.device@3.2.so"
    "*/lib64/android.hardware.camera.device@3.3.so"
    "*/lib64/android.hardware.camera.device@3.4.so"
    "*/lib64/android.hardware.camera.device@3.5.so"
    "*/lib64/android.hardware.camera.device@3.6.so"
    "*/lib64/android.hardware.camera.device@3.7.so"
    "*/lib64/android.hardware.camera.metadata@3.2.so"
    "*/lib64/android.hardware.camera.metadata@3.3.so"
    "*/lib64/android.hardware.camera.metadata@3.4.so"
    "*/lib64/android.hardware.camera.metadata@3.5.so"
    "*/lib64/android.hardware.camera.metadata@3.6.so"
    "*/lib64/android.hardware.camera.provider@2.4-external.so"
    "*/lib64/android.hardware.camera.provider@2.4-legacy.so"
    "*/lib64/android.hardware.camera.provider@2.4.so"
    "*/lib64/android.hardware.camera.provider@2.5.so"
    "*/lib64/android.hardware.camera.provider@2.6.so"
    "*/lib64/android.hardware.camera.provider@2.7.so"
    "*/lib64/camera.device@1.0-impl.so"
    "*/lib64/camera.device@3.2-impl.so"
    "*/lib64/camera.device@3.3-impl.so"
    "*/lib64/camera.device@3.4-external-impl.so"
    "*/lib64/camera.device@3.4-impl.so"
    "*/lib64/camera.device@3.5-external-impl.so"
    "*/lib64/camera.device@3.5-impl.so"
    "*/lib64/camera.device@3.6-external-impl.so"
    "*/lib64/hw/android.hardware.camera.provider@2.7-impl-vcamera.so"
    "*/lib64/libcamera2ndk_vendor.so"
    "*/lib64/vendor.qti.hardware.camera.aon@1.0.so"
    "*/lib64/vendor.qti.hardware.camera.aon@1.1.so"
    "*/lib64/vendor.qti.hardware.camera.aon@1.2.so"
    "*/lib64/vendor.qti.hardware.camera.aon@1.3.so"
    "*/lib64/vendor.qti.hardware.camera.postproc@1.0.so"
    "*/lib/android.frameworks.cameraservice.common@2.0.so"
    "*/lib/android.frameworks.cameraservice.device@2.0.so"
    "*/lib/android.frameworks.cameraservice.device@2.1.so"
    "*/lib/android.frameworks.cameraservice.service@2.0.so"
    "*/lib/android.frameworks.cameraservice.service@2.1.so"
    "*/lib/android.frameworks.cameraservice.service@2.2.so"
    "*/lib/android.hardware.camera.common@1.0.so"
    "*/lib/android.hardware.camera.device@1.0.so"
    "*/lib/android.hardware.camera.device@3.2.so"
    "*/lib/android.hardware.camera.device@3.3.so"
    "*/lib/android.hardware.camera.device@3.4.so"
    "*/lib/android.hardware.camera.device@3.5.so"
    "*/lib/android.hardware.camera.device@3.6.so"
    "*/lib/android.hardware.camera.device@3.7.so"
    "*/lib/android.hardware.camera.metadata@3.2.so"
    "*/lib/android.hardware.camera.metadata@3.3.so"
    "*/lib/android.hardware.camera.metadata@3.4.so"
    "*/lib/android.hardware.camera.metadata@3.5.so"
    "*/lib/android.hardware.camera.metadata@3.6.so"
    "*/lib/android.hardware.camera.provider@2.4-external.so"
    "*/lib/android.hardware.camera.provider@2.4-legacy.so"
    "*/lib/android.hardware.camera.provider@2.4.so"
    "*/lib/android.hardware.camera.provider@2.5.so"
    "*/lib/android.hardware.camera.provider@2.6.so"
    "*/lib/android.hardware.camera.provider@2.7.so"
    "*/lib/camera.device@1.0-impl.so"
    "*/lib/camera.device@3.2-impl.so"
    "*/lib/camera.device@3.3-impl.so"
    "*/lib/camera.device@3.4-external-impl.so"
    "*/lib/camera.device@3.4-impl.so"
    "*/lib/camera.device@3.5-external-impl.so"
    "*/lib/camera.device@3.5-impl.so"
    "*/lib/camera.device@3.6-external-impl.so"
    "*/lib/hw/android.hardware.camera.provider@2.7-impl-vcamera.so"
    "*/lib/libcamera2ndk_vendor.so"

    # Camera files
    "*/etc/audio/test.wav"
    "*/etc/camera/102_SummerDay.png"
    "*/etc/camera/103_Fantasy.png"
    "*/etc/camera/104_Meet.png"
    "*/etc/camera/105_WindSing.png"
    "*/etc/camera/106_Lost.png"
    "*/etc/camera/107_Central.png"
    "*/etc/camera/108_NorthernEurope.png"
    "*/etc/camera/109_Rome.png"
    "*/etc/camera/110_BlackGold.png"
    "*/etc/camera/111_GreenOrange.png"
    "*/etc/camera/112_CyberPunk.png"
    "*/etc/camera/113_BlackIce.png"
    "*/etc/camera/121_Bleach.png"
    "*/etc/camera/122_Thriller.png"
    "*/etc/camera/123_TealOrange.png"
    "*/etc/camera/124_JapaneseStyle.png"
    "*/etc/camera/125_Latin.png"
    "*/etc/camera/126_Fantasy2.png"
    "*/etc/camera/127_Creamy.png"
    "*/etc/camera/128_Sepia.png"
    "*/etc/camera/129_Vivid.png"
    "*/etc/camera/130_Natural.png"
    "*/etc/camera/131_Monochrome.png"
    "*/etc/camera/132_MonochromeHighContrast.png"
    "*/etc/camera/133_MonochromeBrown.png"
    "*/etc/camera/134_MonochromeBlue.png"
    "*/etc/camera/af_class_all.dlc"
    "*/etc/camera/af_class_human.dlc"
    "*/etc/camera/af_classify.dlc"
    "*/etc/camera/af_detect_1st.dlc"
    "*/etc/camera/af_detect_2nd.dlc"
    "*/etc/camera/af_detect_3rd.dlc"
    "*/etc/camera/af_detect_4th.dlc"
    "*/etc/camera/af_detect_5th.dlc"
    "*/etc/camera/af_saliency.dlc"
    "*/etc/camera/af_track_backbone.dlc"
    "*/etc/camera/af_track_head.dlc"
    "*/etc/camera/aivsModels1"
    "*/etc/camera/aivsModels2"
    "*/etc/camera/aivsModels3"
    "*/etc/camera/aivsParams"
    "*/etc/camera/aivsParams2"
    "*/etc/camera/altekldc_packdata_0x01.bin"
    "*/etc/camera/altekldc_segmodel.bin"
    "*/etc/camera/altekldc_tuningdata_ai.bin"
    "*/etc/camera/altekldc_tuningdata.bin"
    "*/etc/camera/deblur_txt_dsp.dlc"
    "*/etc/camera/deblur_txt_gpu.dlc"
    "*/etc/camera/facesr_hd_composite_ref_4.3.15_qcom8550_qnn_segqnn_qnn2.3_qualityv35r2.model"
    "*/etc/camera/mialgo_nn_xmi_slmt_4x_1080p.bin"
    "*/etc/camera/mialgo_nn_xmi_slmt_4x_720p.bin"
    "*/etc/camera/night_align_lsc_tbl_40962304.bin"
    "*/etc/camera/night_align_lsc_tbl_40963072.bin"
    "*/etc/camera/resources/default_param.json"
    "*/etc/camera/resources/kernel/1720888_32.bin"
    "*/etc/camera/resources/kernel/1720888_64.bin"
    "*/etc/camera/resources/kernel/2821809890_32.bin"
    "*/etc/camera/resources/kernel/2821809890_64.bin"
    "*/etc/camera/resources/kernel/32/s31bc24e5f6c4ef1752c77f3a22ad1ffcs0cc175b9c0f1b6a831c399e269772661t92eb5ffee6ae2fec3ad71c777531578fn92eb5ffee6ae2fec3ad71c777531578fn.bin"
    "*/etc/camera/resources/kernel/32/t31bc24e5f6c4ef1752c77f3a22ad1ffcs0cc175b9c0f1b6a831c399e269772661t92eb5ffee6ae2fec3ad71c777531578fn92eb5ffee6ae2fec3ad71c777531578fn.bin"
    "*/etc/camera/resources/kernel/3711416411_32.bin"
    "*/etc/camera/resources/kernel/3711416411_64.bin"
    "*/etc/camera/resources/kernel/64/s31bc24e5f6c4ef1752c77f3a22ad1ffcs0cc175b9c0f1b6a831c399e269772661t92eb5ffee6ae2fec3ad71c777531578fn92eb5ffee6ae2fec3ad71c777531578fn.bin"
    "*/etc/camera/resources/kernel/64/t31bc24e5f6c4ef1752c77f3a22ad1ffcs0cc175b9c0f1b6a831c399e269772661t92eb5ffee6ae2fec3ad71c777531578fn92eb5ffee6ae2fec3ad71c777531578fn.bin"
    "*/etc/camera/resources/model/1031135984"
    "*/etc/camera/resources/model/1711078354"
    "*/etc/camera/resources/model/1966560729"
    "*/etc/camera/resources/model/2192216592"
    "*/etc/camera/resources/model/2242409300"
    "*/etc/camera/resources/model/2405225402"
    "*/etc/camera/resources/model/2722133617"
    "*/etc/camera/resources/model/3606267036"
    "*/etc/camera/resources/model/982209079"
    "*/etc/camera/resources/render/1068495261"
    "*/etc/camera/resources/render/1202823203"
    "*/etc/camera/resources/render/1587396406"
    "*/etc/camera/resources/render/183601851"
    "*/etc/camera/resources/render/1846660881"
    "*/etc/camera/resources/render/2135547585"
    "*/etc/camera/resources/render/2199122872"
    "*/etc/camera/resources/render/2532213662"
    "*/etc/camera/resources/render/2611148883"
    "*/etc/camera/resources/render/2644822710"
    "*/etc/camera/resources/render/3171791906"
    "*/etc/camera/resources/render/33333333"
    "*/etc/camera/resources/render/3533515369"
    "*/etc/camera/resources/render/3626370065"
    "*/etc/camera/resources/render/4183165925"
    "*/etc/camera/resources/render/4224303816"
    "*/etc/camera/resources/render/837151146"
    "*/etc/camera/resources/render/858912661"
    "*/etc/camera/resources/render/Effect/10_ColorTone/Effects/0_ModeClassical/effect.json"
    "*/etc/camera/resources/render/Effect/10_ColorTone/Effects/0_ModeClassical/filter.bin"
    "*/etc/camera/resources/render/Effect/10_ColorTone/Effects/1_ModeNative/effect.json"
    "*/etc/camera/resources/render/Effect/10_ColorTone/Effects/1_ModeNative/filter.bin"
    "*/etc/camera/resources/render/Effect/10_ColorTone/mode_classical.json"
    "*/etc/camera/resources/render/Effect/10_ColorTone/mode_native.json"
    "*/etc/camera/resources/render/Effect/15_DLRetouch/mode_classical.json"
    "*/etc/camera/resources/render/Effect/15_DLRetouch/mode_native.json"
    "*/etc/camera/resources/render/Effect/15_DLRetouch/mode_none.json"
    "*/etc/camera/resources/render/Effect/15_DLRetouch/mode_rear.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/0_Spotless/effect.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/0_Spotless/FaceMask.bin"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/effect.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothNative/effect_capture.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothNative/effect_preview.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothNative/FaceMask.bin"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothNative/FaceMask_Capture.bin"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/effect_capture.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/effect_preview.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/FaceMask.bin"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/4_Hessian/effect.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/4_Hessian/FaceMask.bin"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/mode_classical.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/mode_light.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/mode_native.json"
    "*/etc/camera/resources/render/Effect/20_FaceRetouch/mode_rear.json"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/effect.json"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/LeftEye.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/RightEye.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/effect.json"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/eye_pupil.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/left_eye.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/right_eye.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/1_FacialSmooth/effectV2.json"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/1_FacialSmooth/FaceMask.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/1_FacialSmooth/FacialSmoothMask_first.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/1_FacialSmooth/FacialSmoothMask_second.bin"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/mode_base_all.json"
    "*/etc/camera/resources/render/Effect/30_BasicRetouch/mode_base.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeClassical/effect_capture.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeClassical/effect_preview.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeClassical/xr.bin"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/1_ModeNative/effect_capture.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/1_ModeNative/effect_preview.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/1_ModeNative/xr.bin"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/2_ModeRear/effect_capture.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/2_ModeRear/effect_preview.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/Effects/2_ModeRear/xr.bin"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/mode_classical.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/mode_native.json"
    "*/etc/camera/resources/render/Effect/40_FaceStereo/mode_rear.json"
    "*/etc/camera/resources/render/Effect/50_SkinTone/Effects/0_ModeClassical/effect.json"
    "*/etc/camera/resources/render/Effect/50_SkinTone/Effects/0_ModeClassical/filter.bin"
    "*/etc/camera/resources/render/Effect/50_SkinTone/Effects/1_ModeNative/effect.json"
    "*/etc/camera/resources/render/Effect/50_SkinTone/Effects/1_ModeNative/filter.bin"
    "*/etc/camera/resources/render/Effect/50_SkinTone/mode_classical.json"
    "*/etc/camera/resources/render/Effect/50_SkinTone/mode_native.json"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/effect_capture.json"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/effect_preview.json"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/Eyebrow.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/sh.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/yyy.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/yyz.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeClassical/zc.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/effect_capture.json"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/effect_preview.json"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/Eyebrow.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/sh.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/yyy.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/yyz.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeNative/zc.bin"
    "*/etc/camera/resources/render/Effect/60_Makeup/mode_classical.json"
    "*/etc/camera/resources/render/Effect/60_Makeup/mode_native.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeClassical/effect_capture.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeClassical/effect_preview.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeClassical/eye_refine.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeClassical/facelift.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeClassical/nose.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/1_ModeNative/effect_capture.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/1_ModeNative/effect_preview.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/1_ModeNative/eye_refine.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/1_ModeNative/facelift.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/1_ModeNative/nose.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/2_ModeOtherFront/effect_capture.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/2_ModeOtherFront/effect_preview.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/2_ModeOtherFront/eye_refine.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/2_ModeOtherFront/facelift.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/3_ModeVideo/effect.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/3_ModeVideo/eye_refine.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/3_ModeVideo/facelift.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/4_ModeRear/effect_capture.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/4_ModeRear/effect_preview.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/Effects/4_ModeRear/eye_refine.bin"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/mode_classical.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/mode_native.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/mode_other_front.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/mode_rear.json"
    "*/etc/camera/resources/render/Effect/70_FacialRefine/mode_video.json"
    "*/etc/camera/resources/render/Effect/effect_list.json"
    "*/etc/camera/resources/render/Effect/effect_mode_classical.json"
    "*/etc/camera/resources/render/Effect/effect_mode_clear.json"
    "*/etc/camera/resources/render/Effect/effect_mode_native.json"
    "*/etc/camera/resources/render/Effect/effect_mode_otherFront.json"
    "*/etc/camera/resources/render/Effect/effect_mode_otherRear.json"
    "*/etc/camera/resources/render/Effect/effect_mode_video.json"
    "*/etc/camera/resources/render/GlobalConfig.json"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_1D_GAUSS_BILATERAL_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_1D_GAUSSBLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_ADVANCE_BRIGHT_EYE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_ADVANCE_BRIGHT_EYEV3_PROC_PUPIL.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_ADVANCE_GUIDE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BASE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BASE_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BASIC_TEXTURE_MAPPING.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BASIC_TEXTURE_MAPPING_Define_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_COLORLAYER_WITHMASK_Define_NORMAL_MASK_R_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_COLORLAYER_WITHMASK_Define_NORMAL_MASK_R_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_MULTIPLY_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_MULTIPLY_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_SOFT_LIGHT_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_SOFT_LIGHT_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_MULTIPLY_MASK_R_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_MULTIPLY_MASK_R_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_SOFT_LIGHT_MASK_R_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_SOFT_LIGHT_MASK_R_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_BOX_FILTER_2X2.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_COLOR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_CONTRAST_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACERETOUCH_LUMA_TO_ALPHA_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACESURGERY_HEADNARROW.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACESURGERY_HEADNARROW_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACESURGERY_HEADNARROW_Define_SMOOTH_COORD.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACESURGERY_HEADNARROW_Define_SMOOTH_COORD_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_NORMAL_FUSE_OFFSETS.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET_Define_NEED_REFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET_Define_USE_SPLIT.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET_Define_USE_SPLIT_NEED_REFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_EYE_FUSE_OFFSET.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_EYE_FUSE_OFFSET_Define_NEED_REFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_LIQUID.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FOGGY_FACERETOUCH_1D_MEANBLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FOGGY_FACERETOUCH_1D_MEANBLUR_Define_USE_ALPHA_WEIGHT.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FOGGY_FACERETOUCH_ADVANCE_PROCESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FOGGY_FACERETOUCH_SIMPLE_PROCESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_FOGGY_FACERETOUCH_VARIANCE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_HESSIAN_FACERETOUCH_PROCESS.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_HESSIAN_FILTER.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_ROTATE_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_ROTATE_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_SCALE_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_SCALE_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_TRANSLATE_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LOCAL_WARP_TRANSLATE_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_LUT_3D_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_MEAN_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_MEDIAN_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_MERGE_MASK.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_POINT.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_SPOTLESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_TEXTURE_RETOUCH_PROCESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_WARP_AFFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_WARP_AFFINE_INCREMENTAL.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_WARP_NORMAL.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_GLPROGRAM_WARP_NORMAL_Define_WARP_TO_ROI.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_RGBA2RGBAUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_RGBA2YUVUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_RGBA2YUVUtils_SWAP_UV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_YUV2RGBAUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_YUV2RGBAUtils_DEHAZE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_YUV2RGBAUtils_SWAP_UV.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_YUV2RGBAUtils_SWAP_UV_DEHAZE.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_YUV2YUVUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders32/shader_YUV2YUVUtils_SWAP_UV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_1D_GAUSS_BILATERAL_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_1D_GAUSSBLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_ADVANCE_BRIGHT_EYE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_ADVANCE_BRIGHT_EYEV3_PROC_PUPIL.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_ADVANCE_GUIDE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BASE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BASE_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BASIC_TEXTURE_MAPPING.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BASIC_TEXTURE_MAPPING_Define_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_COLORLAYER_WITHMASK_Define_NORMAL_MASK_R_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_COLORLAYER_WITHMASK_Define_NORMAL_MASK_R_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_MULTIPLY_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_MULTIPLY_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_SOFT_LIGHT_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_NORMAL_Define_SOFT_LIGHT_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_MULTIPLY_MASK_R_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_MULTIPLY_MASK_R_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_SOFT_LIGHT_MASK_R_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BLEND_IMAGELAYER_WITHMASK_Define_SOFT_LIGHT_MASK_R_FRAMEBUFFER_FETCH_ADRENO_BLEND_ALPHA.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_BOX_FILTER_2X2.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_COLOR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_CONTRAST_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACERETOUCH_LUMA_TO_ALPHA_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACESURGERY_HEADNARROW.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACESURGERY_HEADNARROW_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACESURGERY_HEADNARROW_Define_SMOOTH_COORD.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACESURGERY_HEADNARROW_Define_SMOOTH_COORD_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_NORMAL_FUSE_OFFSETS.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_NORMAL_WARP_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET_Define_NEED_REFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET_Define_USE_SPLIT.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_BASE_FUSE_OFFSET_Define_USE_SPLIT_NEED_REFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_EYE_FUSE_OFFSET.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_EYE_FUSE_OFFSET_Define_NEED_REFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_DEF_M_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_LIQUID.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FACIALREFINE_V2_WARP_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FOGGY_FACERETOUCH_1D_MEANBLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FOGGY_FACERETOUCH_1D_MEANBLUR_Define_USE_ALPHA_WEIGHT.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FOGGY_FACERETOUCH_ADVANCE_PROCESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FOGGY_FACERETOUCH_SIMPLE_PROCESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_FOGGY_FACERETOUCH_VARIANCE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_HESSIAN_FACERETOUCH_PROCESS.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_HESSIAN_FILTER.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_ROTATE_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_ROTATE_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_SCALE_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_SCALE_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_TRANSLATE_Define_USE_EG_PRESERV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LOCAL_WARP_TRANSLATE_Define_USE_EG_PRESERV_DEF_CATMULL_ROM.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_LUT_3D_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_MEAN_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_MEDIAN_BLUR.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_MERGE_MASK.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_POINT.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_SPOTLESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_TEXTURE_RETOUCH_PROCESS_Define_FRAMEBUFFER_FETCH_ADRENO.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_WARP_AFFINE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_WARP_AFFINE_INCREMENTAL.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_WARP_NORMAL.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_GLPROGRAM_WARP_NORMAL_Define_WARP_TO_ROI.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_RGBA2RGBAUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_RGBA2YUVUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_RGBA2YUVUtils_SWAP_UV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_YUV2RGBAUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_YUV2RGBAUtils_DEHAZE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_YUV2RGBAUtils_SWAP_UV.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_YUV2RGBAUtils_SWAP_UV_DEHAZE.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_YUV2YUVUtils.bin"
    "*/etc/camera/resources/render/glsl/binShaders64/shader_YUV2YUVUtils_SWAP_UV.bin"
    "*/etc/camera/resources/truesight_param_debug.json"
    "*/etc/camera/resources/truesight_param.json"
    "*/etc/camera/snsc.bin"
    "*/etc/camera/xmi_slmt_4x_1080p.dlc"
    "*/etc/camera/xmi_slmt_4x_720p.dlc"
    "*/etc/merged_language_model.lat"
    "*/etc/XiaoAiNiZaiNa.uim"
    "*/etc/XiaoAiTongXue.uim"
    "*/lib64/libarcsoft_bokeh_high_dynamic_range.so"
    "*/lib64/libarcsoft_dualcam_refocus_image.so"
    "*/lib64/libarcsoft_super_night_raw.so"
    "*/lib64/libmiai_deblur.so"
    "*/lib64/libmiai_portraitsupernight.so"
    "*/lib64/libportrait_repair_qnn.so"
    "*/lib64/libsupermoon.so"
    "*/lib64/libTrueSight.so"
    "*/lib64/libxmi_hdr_checker.so"
    "*/lib64/libxmi_high_dynamic_range_cdsp.so"
    "*/lib64/libxmi_high_dynamic_range.so"
    "*/lib64/libxmi_slow_motion_mein.so"
    "*/lib64/libxmi_slow_motion_triger.so"
    "*/lib/camera/com.qti.tuned.default.bin"
    "*/lib/camera/com.qti.tuned.socrates_ofilm_ov08d10_ultra.bin"
    "*/lib/camera/com.qti.tuned.socrates_ofilm_ov16a1q_front.bin"
    "*/lib/camera/com.qti.tuned.socrates_semco_imx800_wide.bin"
    "*/lib/camera/com.qti.tuned.socrates_sunny_ov02b10_macro.bin"
    "*/lib/camera/com.qti.tuned.tpg.bin"

    # CAS
    "*/bin/hw/android.hardware.cas@1.2-service"
    "*/etc/init/android.hardware.cas@1.2-service.rc"
    "*/etc/vintf/manifest/android.hardware.cas@1.2-service.xml"
    "*/lib/android.hardware.cas@1.0.so"
    "*/lib/android.hardware.cas@1.1.so"
    "*/lib/android.hardware.cas@1.2.so"
    "*/lib/android.hardware.cas.native@1.0.so"

    # Charger
    "*/etc/res/images/default/charger/battery_fail.png"
    "*/etc/res/images/default/charger/battery_scale.png"

    # Display
    "*/lib64/android.hardware.graphics.composer@2.1.so"
    "*/lib64/android.hardware.graphics.composer@2.2.so"
    "*/lib64/android.hardware.graphics.composer@2.3.so"
    "*/lib64/android.hardware.graphics.composer@2.4.so"
    "*/lib64/libdrm.so"
    "*/lib64/vendor.display.config@1.0.so"
    "*/lib64/vendor.display.config@1.10.so"
    "*/lib64/vendor.display.config@1.11.so"
    "*/lib64/vendor.display.config@1.1.so"
    "*/lib64/vendor.display.config@1.2.so"
    "*/lib64/vendor.display.config@1.3.so"
    "*/lib64/vendor.display.config@1.4.so"
    "*/lib64/vendor.display.config@1.5.so"
    "*/lib64/vendor.display.config@1.6.so"
    "*/lib64/vendor.display.config@1.7.so"
    "*/lib64/vendor.display.config@1.8.so"
    "*/lib64/vendor.display.config@1.9.so"
    "*/lib64/vendor.display.config@2.0.so"
    "*/lib64/vendor.qti.hardware.display.allocator@1.0.so"
    "*/lib64/vendor.qti.hardware.display.allocator@3.0.so"
    "*/lib64/vendor.qti.hardware.display.allocator@4.0.so"
    "*/lib64/vendor.qti.hardware.display.composer@1.0.so"
    "*/lib64/vendor.qti.hardware.display.composer@2.0.so"
    "*/lib64/vendor.qti.hardware.display.composer@3.0.so"
    "*/lib64/vendor.qti.hardware.display.composer@3.1.so"
    "*/lib64/vendor.qti.hardware.display.demura@2.0.so"
    "*/lib64/vendor.qti.hardware.display.mapper@1.0.so"
    "*/lib64/vendor.qti.hardware.display.mapper@1.1.so"
    "*/lib64/vendor.qti.hardware.display.mapper@2.0.so"
    "*/lib64/vendor.qti.hardware.display.mapper@3.0.so"
    "*/lib64/vendor.qti.hardware.display.mapper@4.0.so"
    "*/lib64/vendor.qti.hardware.display.mapperextensions@1.0.so"
    "*/lib64/vendor.qti.hardware.display.mapperextensions@1.1.so"
    "*/lib64/vendor.qti.hardware.display.mapperextensions@1.2.so"
    "*/lib64/vendor.qti.hardware.display.mapperextensions@1.3.so"
    "*/lib/android.hardware.graphics.composer@2.1.so"
    "*/lib/android.hardware.graphics.composer@2.2.so"
    "*/lib/android.hardware.graphics.composer@2.3.so"
    "*/lib/android.hardware.graphics.composer@2.4.so"
    "*/lib/libdrm.so"
    "*/lib/vendor.display.config@1.0.so"
    "*/lib/vendor.display.config@1.10.so"
    "*/lib/vendor.display.config@1.11.so"
    "*/lib/vendor.display.config@1.1.so"
    "*/lib/vendor.display.config@1.2.so"
    "*/lib/vendor.display.config@1.3.so"
    "*/lib/vendor.display.config@1.4.so"
    "*/lib/vendor.display.config@1.5.so"
    "*/lib/vendor.display.config@1.6.so"
    "*/lib/vendor.display.config@1.7.so"
    "*/lib/vendor.display.config@1.8.so"
    "*/lib/vendor.display.config@1.9.so"
    "*/lib/vendor.display.config@2.0.so"
    "*/lib/vendor.qti.hardware.display.allocator@1.0.so"
    "*/lib/vendor.qti.hardware.display.allocator@3.0.so"
    "*/lib/vendor.qti.hardware.display.allocator@4.0.so"
    "*/lib/vendor.qti.hardware.display.composer@1.0.so"
    "*/lib/vendor.qti.hardware.display.composer@2.0.so"
    "*/lib/vendor.qti.hardware.display.composer@3.0.so"
    "*/lib/vendor.qti.hardware.display.demura@2.0.so"
    "*/lib/vendor.qti.hardware.display.mapper@1.0.so"
    "*/lib/vendor.qti.hardware.display.mapper@1.1.so"
    "*/lib/vendor.qti.hardware.display.mapper@2.0.so"
    "*/lib/vendor.qti.hardware.display.mapper@3.0.so"
    "*/lib/vendor.qti.hardware.display.mapper@4.0.so"
    "*/lib/vendor.qti.hardware.display.mapperextensions@1.0.so"
    "*/lib/vendor.qti.hardware.display.mapperextensions@1.1.so"
    "*/lib/vendor.qti.hardware.display.mapperextensions@1.2.so"
    "*/lib/vendor.qti.hardware.display.mapperextensions@1.3.so"

    # DRM
    "*/bin/hw/android.hardware.drm-service.clearkey"
    "*/etc/init/android.hardware.drm-service.clearkey.rc"
    "*/etc/vintf/manifest/android.hardware.drm-service.clearkey.xml"
    "*/lib64/android.hardware.drm@1.0.so"
    "*/lib64/android.hardware.drm@1.1.so"
    "*/lib64/android.hardware.drm@1.2.so"
    "*/lib64/android.hardware.drm@1.3.so"

    # Filesystem
    "*/etc/fs_config_dirs"
    "*/etc/fs_config_files"
    "*/lib64/libext2_uuid.so"
    "*/lib64/libsparse.so"
    "*/lib/libext2_uuid.so"
    "*/lib/libsparse.so"

    # Framework detect
    "*/lib64/libqti_vndfwk_detect.so"
    "*/lib64/libqti_vndfwk_detect_vendor.so"
    "*/lib64/libvndfwk_detect_jni.qti.so"
    "*/lib64/libvndfwk_detect_jni.qti_vendor.so"
    "*/lib/libqti_vndfwk_detect.so"
    "*/lib/libqti_vndfwk_detect_vendor.so"
    "*/lib/libvndfwk_detect_jni.qti.so"
    "*/lib/libvndfwk_detect_jni.qti_vendor.so"

    # FSTAB
    "*/etc/fstab.qcom"

    # Graphics
    "*/lib64/hw/gralloc.default.so"
    "*/lib/hw/gralloc.default.so"

    # GUI
    "*/lib64/libgui_vendor.so"
    "*/lib/libgui_vendor.so"

    # Health
    "*/bin/hw/android.hardware.health-service.qti"
    "*/etc/init/android.hardware.health-service.qti.rc"
    "*/etc/vintf/manifest/android.hardware.health-service.qti.xml"
    "*/lib64/android.hardware.health@1.0.so"
    "*/lib64/android.hardware.health@2.0.so"
    "*/lib64/android.hardware.health@2.1.so"
    "*/lib/android.hardware.health@1.0.so"
    "*/lib/android.hardware.health@2.0.so"
    "*/lib/android.hardware.health@2.1.so"

    # HIDL
    "*/lib64/android.hidl.allocator@1.0.so"
    "*/lib64/android.hidl.memory.block@1.0.so"
    "*/lib64/libhidltransport.so"
    "*/lib64/libhwbinder.so"
    "*/lib/android.hidl.allocator@1.0.so"
    "*/lib/android.hidl.memory.block@1.0.so"
    "*/lib/libhidltransport.so"
    "*/lib/libhwbinder.so"

    # IPA
    "*/bin/ipacm"
    "*/etc/init/ipacm.rc"
    "*/etc/IPACM_cfg.xml"
    "*/etc/IPACM_Filter_cfg.xml"

    # IR
    "*/bin/hw/android.hardware.ir-service.example"
    "*/etc/init/android.hardware.ir-service.example.rc"
    "*/etc/vintf/manifest/android.hardware.ir-service.example.xml"

    # JSON
    "*/lib64/libjson.so"
    "*/lib/libjson.so"

    # Libchrome
    "*/lib64/libchrome.so"

    # Media
    "*/bin/hw/android.hardware.media.omx@1.0-service"
    "*/etc/init/android.hardware.media.omx@1.0-service.rc"
    "*/lib64/android.hardware.media.c2@1.0.so"
    "*/lib64/android.hardware.media.c2@1.1.so"
    "*/lib64/android.hardware.media.c2@1.2.so"
    "*/lib64/libavservices_minijail.so"
    "*/lib64/libcodec2_hidl_plugin.so"
    "*/lib64/libcodec2_soft_common.so"
    "*/lib64/libcodec2_vndk.so"
    "*/lib64/libCOSNet_spatial_qnn_quantized.so"
    "*/lib64/libeffectsconfig.so"
    "*/lib64/libeffects.so"
    "*/lib64/libmediautils_vendor.so"
    "*/lib64/libmm-omxcore.so"
    "*/lib64/libOmxCore.so"
    "*/lib64/libsfplugin_ccodec_utils.so"
    "*/lib64/libstagefright_bufferpool@2.0.1.so"
    "*/lib64/libstagefrighthw.so"
    "*/lib64/mediacas/libclearkeycasplugin.so"
    "*/lib64/mediadrm/libdrmclearkeyplugin.so"
    "*/lib64/soundfx/libeffectproxy.so"
    "*/lib/android.hardware.media.c2@1.0.so"
    "*/lib/libavservices_minijail.so"
    "*/lib/libcodec2_hidl_plugin.so"
    "*/lib/libcodec2_vndk.so"
    "*/lib/libeffectsconfig.so"
    "*/lib/libeffects.so"
    "*/lib/libmediautils_vendor.so"
    "*/lib/libmm-omxcore.so"
    "*/lib/libOmxCore.so"
    "*/lib/libopus.so"
    "*/lib/libsfplugin_ccodec_utils.so"
    "*/lib/libstagefright_amrnb_common.so"
    "*/lib/libstagefright_bufferpool@2.0.1.so"
    "*/lib/libstagefright_enc_common.so"
    "*/lib/libstagefright_flacdec.so"
    "*/lib/libstagefrighthw.so"
    "*/lib/libstagefright_soft_aacdec.so"
    "*/lib/libstagefright_soft_aacenc.so"
    "*/lib/libstagefright_soft_amrdec.so"
    "*/lib/libstagefright_soft_amrnbenc.so"
    "*/lib/libstagefright_soft_amrwbenc.so"
    "*/lib/libstagefright_soft_avcdec.so"
    "*/lib/libstagefright_soft_avcenc.so"
    "*/lib/libstagefright_soft_flacdec.so"
    "*/lib/libstagefright_soft_flacenc.so"
    "*/lib/libstagefright_soft_g711dec.so"
    "*/lib/libstagefright_soft_gsmdec.so"
    "*/lib/libstagefright_soft_hevcdec.so"
    "*/lib/libstagefright_soft_mp3dec.so"
    "*/lib/libstagefright_soft_mpeg2dec.so"
    "*/lib/libstagefright_soft_mpeg4dec.so"
    "*/lib/libstagefright_soft_mpeg4enc.so"
    "*/lib/libstagefright_softomx_plugin.so"
    "*/lib/libstagefright_softomx.so"
    "*/lib/libstagefright_soft_opusdec.so"
    "*/lib/libstagefright_soft_rawdec.so"
    "*/lib/libstagefright_soft_vorbisdec.so"
    "*/lib/libstagefright_soft_vpxdec.so"
    "*/lib/libstagefright_soft_vpxenc.so"
    "*/lib/libvorbisidec.so"
    "*/lib/libvpx.so"
    "*/lib/mediacas/libclearkeycasplugin.so"
    "*/lib/mediadrm/libdrmclearkeyplugin.so"
    "*/lib/soundfx/libeffectproxy.so"

    # Memtrack
    "*/bin/hw/vendor.qti.hardware.memtrack-service"
    "*/etc/init/memtrack_qti.rc"
    "*/etc/vintf/manifest/memtrack_qti.xml"

    # Misc
    "*/etc/group"
    "*/etc/passwd"

    # Network
    "*/lib64/android.system.net.netd@1.0.so"
    "*/lib64/android.system.net.netd@1.1.so"
    "*/lib64/libnetfilter_conntrack.so"
    "*/lib64/libnfnetlink.so"
    "*/lib64/libpcap.so"
    "*/lib/android.system.net.netd@1.0.so"
    "*/lib/android.system.net.netd@1.1.so"

    # Notice files
    "*/etc/NOTICE.xml.gz"

    # NFC
    "*/bin/nqnfcinfo"
    "*/lib64/android.hardware.nfc@1.0.so"
    "*/lib64/android.hardware.nfc@1.1.so"
    "*/lib64/android.hardware.nfc@1.2.so"
    "*/lib/android.hardware.nfc@1.0.so"
    "*/lib/android.hardware.nfc@1.1.so"
    "*/lib/android.hardware.nfc@1.2.so"

    # Overlays
    "*/overlay/FrameworksResTarget_Vendor.apk"
    "*/overlay/SecureElementResTarget_Vendor.apk"
    "*/overlay/WifiResTarget.apk"
    "*/overlay/WifiResTarget_spf.apk"

    # Power
    "*/lib64/android.hardware.power@1.0.so"
    "*/lib64/android.hardware.power@1.1.so"
    "*/lib64/android.hardware.power@1.2.so"
    "*/lib64/android.hardware.power-V4-ndk.so"
    "*/lib64/hw/power.default.so"
    "*/lib64/vendor.qti.hardware.perf@2.0.so"
    "*/lib64/vendor.qti.hardware.perf@2.1.so"
    "*/lib64/vendor.qti.hardware.perf@2.2.so"
    "*/lib64/vendor.qti.hardware.perf@2.3.so"
    "*/lib/android.hardware.power@1.0.so"
    "*/lib/android.hardware.power@1.1.so"
    "*/lib/android.hardware.power@1.2.so"
    "*/lib/hw/power.default.so"
    "*/lib/vendor.qti.hardware.perf@2.0.so"
    "*/lib/vendor.qti.hardware.perf@2.1.so"
    "*/lib/vendor.qti.hardware.perf@2.2.so"
    "*/lib/vendor.qti.hardware.perf@2.3.so"

    # ProtoBuf
    "*/lib64/libprotobuf-cpp-full-3.9.1.so"
    "*/lib64/libprotobuf-cpp-lite-3.9.1.so"
    "*/lib/libprotobuf-cpp-full-3.9.1.so"
    "*/lib/libprotobuf-cpp-lite-3.9.1.so"

    # PSI
    "*/lib64/libpsi.so"
    "*/lib/libpsi.so"

    # Radio
    "*/lib64/android.hardware.radio@1.0.so"
    "*/lib64/android.hardware.radio@1.1.so"
    "*/lib64/android.hardware.radio@1.2.so"
    "*/lib64/android.hardware.radio@1.3.so"
    "*/lib64/android.hardware.radio@1.4.so"
    "*/lib64/android.hardware.radio@1.5.so"
    "*/lib64/android.hardware.radio@1.6.so"
    "*/lib64/libreference-ril.so"
    "*/lib64/libril.so"
    "*/lib64/librilutils.so"
    "*/lib/android.hardware.radio@1.0.so"
    "*/lib/android.hardware.radio@1.1.so"
    "*/lib/android.hardware.radio@1.2.so"
    "*/lib/android.hardware.radio@1.3.so"
    "*/lib/android.hardware.radio@1.4.so"
    "*/lib/android.hardware.radio@1.5.so"
    "*/lib/android.hardware.radio@1.6.so"
    "*/lib/libreference-ril.so"
    "*/lib/libril.so"
    "*/lib/librilutils.so"

    # RenderScript
    "*/lib64/hw/android.hardware.renderscript@1.0-impl.so"
    "*/lib/hw/android.hardware.renderscript@1.0-impl.so"

    # SecureElement
    "*/lib64/android.hardware.secure_element@1.0.so"
    "*/lib64/android.hardware.secure_element@1.1.so"
    "*/lib64/android.hardware.secure_element@1.2.so"
    "*/lib/android.hardware.secure_element@1.0.so"
    "*/lib/android.hardware.secure_element@1.1.so"
    "*/lib/android.hardware.secure_element@1.2.so"

    # Security
    "*/etc/permissions/android.hardware.hardware_keystore.xml"
    "*/lib64/android.hardware.gatekeeper@1.0.so"
    "*/lib64/android.hardware.keymaster@3.0.so"
    "*/lib64/android.hardware.keymaster@4.0.so"
    "*/lib64/android.hardware.keymaster@4.1.so"
    "*/lib64/android.hardware.security.keymint-V1-ndk.so"
    "*/lib64/android.system.keystore2-V1-ndk.so"
    "*/lib64/libkeymaster_messages.so"
    "*/lib/android.hardware.gatekeeper@1.0.so"
    "*/lib/android.hardware.keymaster@3.0.so"
    "*/lib/android.hardware.keymaster@4.0.so"
    "*/lib/android.hardware.keymaster@4.1.so"
    "*/lib/libkeymaster_messages.so"

    # SELinux
    "*/etc/selinux/odm_file_contexts"
    "*/etc/selinux/odm_hwservice_contexts"
    "*/etc/selinux/odm_mac_permissions.xml"
    "*/etc/selinux/odm_property_contexts"
    "*/etc/selinux/odm_seapp_contexts"
    "*/etc/selinux/odm_sepolicy.cil"
    "*/etc/selinux/plat_pub_versioned.cil"
    "*/etc/selinux/plat_sepolicy_vers.txt"
    "*/etc/selinux/precompiled_sepolicy"
    "*/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256"
    "*/etc/selinux/precompiled_sepolicy.product_sepolicy_and_mapping.sha256"
    "*/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256"
    "*/etc/selinux/selinux_denial_metadata"
    "*/etc/selinux/vendor_file_contexts"
    "*/etc/selinux/vendor_hwservice_contexts"
    "*/etc/selinux/vendor_mac_permissions.xml"
    "*/etc/selinux/vendor_property_contexts"
    "*/etc/selinux/vendor_seapp_contexts"
    "*/etc/selinux/vendor_sepolicy.cil"
    "*/etc/selinux/vendor_service_contexts"
    "*/etc/selinux/vndservice_contexts"

    # Sensors
    "*/bin/hw/android.hardware.sensors-service.multihal"
    "*/etc/init/android.hardware.sensors-service-multihal.rc"
    "*/etc/vintf/manifest/android.hardware.sensors-multihal.xml"
    "*/lib64/android.frameworks.sensorservice@1.0.so"
    "*/lib64/android.hardware.sensors@1.0.so"
    "*/lib64/android.hardware.sensors@2.0-ScopedWakelock.so"
    "*/lib64/android.hardware.sensors@2.0.so"
    "*/lib64/android.hardware.sensors@2.1.so"
    "*/lib64/hw/sensors.dynamic_sensor_hal.so"
    "*/lib64/libhidparser.so"
    "*/lib64/libsensorndkbridge.so"
    "*/lib/android.frameworks.sensorservice@1.0.so"
    "*/lib/android.hardware.sensors@1.0.so"
    "*/lib/android.hardware.sensors@2.0-ScopedWakelock.so"
    "*/lib/android.hardware.sensors@2.0.so"
    "*/lib/android.hardware.sensors@2.1.so"
    "*/lib/hw/sensors.dynamic_sensor_hal.so"
    "*/lib/libhidparser.so"

    # ServiceTracker
    "*/lib64/vendor.qti.hardware.servicetracker@1.0.so"
    "*/lib64/vendor.qti.hardware.servicetracker@1.1.so"
    "*/lib64/vendor.qti.hardware.servicetracker@1.2.so"
    "*/lib/vendor.qti.hardware.servicetracker@1.0.so"
    "*/lib/vendor.qti.hardware.servicetracker@1.1.so"
    "*/lib/vendor.qti.hardware.servicetracker@1.2.so"

    # Tethering
    "*/lib64/android.hardware.tetheroffload.config@1.0.so"
    "*/lib64/android.hardware.tetheroffload.control@1.0.so"
    "*/lib64/android.hardware.tetheroffload.control@1.1.so"

    # Thermal
    "*/bin/hw/android.hardware.thermal@2.0-service.qti-v2"
    "*/etc/init/android.hardware.thermal@2.0-service.qti-v2.rc"
    "*/etc/vintf/manifest/android.hardware.thermal@2.0-service.qti.xml"
    "*/lib64/android.hardware.thermal@1.0.so"
    "*/lib64/android.hardware.thermal@2.0.so"
    "*/lib/android.hardware.thermal@1.0.so"
    "*/lib/android.hardware.thermal@2.0.so"

    # Time
    "*/lib64/hw/local_time.default.so"
    "*/lib/hw/local_time.default.so"

    # TLPd
    "*/bin/tlpd"
    "*/etc/init/tlpd.rc"
    "*/lib64/libtlpd_configmgr.so"
    "*/lib64/libtlpd_crypto.so"
    "*/lib64/libtlpd_internal.so"
    "*/lib64/libtlpd_logger.so"
    "*/lib64/libtlpd.so"

    # Touch
    "*/bin/touch_report"

    # TrustedUI
    "*/lib64/vendor.qti.hardware.systemhelper@1.0.so"
    "*/lib/vendor.qti.hardware.systemhelper@1.0.so"

    # USB
    "*/bin/hw/android.hardware.usb.gadget@1.1-service-qti"
    "*/etc/init/android.hardware.usb.gadget@1.1-service-qti.rc"
    "*/etc/usb_compositions.conf"
    "*/etc/vintf/manifest/android.hardware.usb.gadget@1.1-service.xml"
    "*/lib64/android.hardware.usb@1.0.so"
    "*/lib64/android.hardware.usb@1.1.so"
    "*/lib64/android.hardware.usb@1.2.so"
    "*/lib64/android.hardware.usb.gadget@1.0.so"
    "*/lib64/android.hardware.usb.gadget@1.1.so"
    "*/lib64/hw/audio.usb.default.so"
    "*/lib/hw/audio.usb.default.so"

    # Vendor binaries
    "*/bin/awk"
    "*/bin/boringssl_self_test32"
    "*/bin/boringssl_self_test64"
    "*/bin/checkpoint_gc"
    "*/bin/cplay"
    "*/bin/dumpsys"
    "*/bin/iw"
    "*/bin/iwconfig"
    "*/bin/iwlist"
    "*/bin/iwpriv"
    "*/bin/logwrapper"
    "*/bin/sh"
    "*/bin/show_reserved_mem"
    "*/bin/shsusrd"
    "*/bin/tcpdump"
    "*/bin/toolbox"
    "*/bin/toybox_vendor"
    "*/etc/mkshrc"
    "*/lib64/libbinderdebug.so"

    # Vendor service manager
    "*/bin/vndservice"
    "*/bin/vndservicemanager"
    "*/etc/init/vndservicemanager.rc"

    # Vibrator
    "*/bin/hw/vendor.xiaomi.hardware.vibratorfeature.service"
    "*/etc/init/vendor.xiaomi.hardware.vibratorfeature.service.rc"
    "*/etc/permissions/vendor.hardware.vibratorfeature-permission.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.vibratorfeature.service.xml"
    "*/firmware/0_click_P_RTP.bin"
    "*/firmware/101_offlineCountdown_P_RTP.bin"
    "*/firmware/102_sceneBombInjury_P_RTP.bin"
    "*/firmware/103_sceneBomb_P_RTP.bin"
    "*/firmware/104_doorOpen_P_RTP.bin"
    "*/firmware/106_sceneStep_P_RTP.bin"
    "*/firmware/107_crawl_P_RTP.bin"
    "*/firmware/108_scopeOn_P_RTP.bin"
    "*/firmware/109_scopeOff_P_RTP.bin"
    "*/firmware/10_ringTone4_RTP.bin"
    "*/firmware/110_magazineQuick_P_RTP.bin"
    "*/firmware/111_grenade_P_RTP.bin"
    "*/firmware/112_sceneGetshot_P_RTP.bin"
    "*/firmware/113_grenadeExplosion_P_RTP.bin"
    "*/firmware/114_punch_P_RTP.bin"
    "*/firmware/115_pan_P_RTP.bin"
    "*/firmware/116_bandage_P_RTP.bin"
    "*/firmware/118_sceneJump_P_RTP.bin"
    "*/firmware/119_vehiclePlane_P_RTP.bin"
    "*/firmware/11_ringTone4_RTP.bin"
    "*/firmware/120_sceneOpenparachute_P_RTP.bin"
    "*/firmware/121_sceneCloseparachute_P_RTP.bin"
    "*/firmware/122_vehicleCollision_P_RTP.bin"
    "*/firmware/123_vehicleBuggy_P_RTP.bin"
    "*/firmware/124_vehicleDacia_P_RTP.bin"
    "*/firmware/125_vehicleMoto_P_RTP.bin"
    "*/firmware/126_firearmsAkm_P_RTP.bin"
    "*/firmware/127_firearmsM16a4_P_RTP.bin"
    "*/firmware/128_firearmsAwm_P_RTP.bin"
    "*/firmware/12_ringTone4_RTP.bin"
    "*/firmware/130_firearmsMini14_P_RTP.bin"
    "*/firmware/131_firearmsVss_P_RTP.bin"
    "*/firmware/132_firearmsQbz_P_RTP.bin"
    "*/firmware/133_firearmsUmp9_P_RTP.bin"
    "*/firmware/134_firearmsDp28_P_RTP.bin"
    "*/firmware/135_firearmsS1897_P_RTP.bin"
    "*/firmware/137_firearmsP18c_P_RTP.bin"
    "*/firmware/13_ringTone4_RTP.bin"
    "*/firmware/140_cfmKillOne_P_RTP.bin"
    "*/firmware/141_cfmHeadshot_P_RTP.bin"
    "*/firmware/142_cfmMultiKill_P_RTP.bin"
    "*/firmware/143_cfmKillOneStrong_P_RTP.bin"
    "*/firmware/144_cfmHeadshotStrong_P_RTP.bin"
    "*/firmware/145_cfmMultiKillStrong_P_RTP.bin"
    "*/firmware/146_cfmWeaponGrenadeExplode_P_RTP.bin"
    "*/firmware/147_cfmWeaponGrenadeKillOne_P_RTP.bin"
    "*/firmware/148_cfmImpactFleshNormal_P_RTP.bin"
    "*/firmware/149_cfmWeaponC4Installed_P_RTP.bin"
    "*/firmware/14_ringTone4_RTP.bin"
    "*/firmware/150_cfmHeroAppear_P_RTP.bin"
    "*/firmware/151_cfmUIRewardOpenBox_P_RTP.bin"
    "*/firmware/152_cfmUIRewardTask_P_RTP.bin"
    "*/firmware/153_cfmWeaponBLTShoot_P_RTP.bin"
    "*/firmware/154_Atlantis_P_RTP.bin"
    "*/firmware/155_DigitalUniverse_P_RTP.bin"
    "*/firmware/156_Reveries_P_RTP.bin"
    "*/firmware/157_fodMotionTriang_P_RTP.bin"
    "*/firmware/158_fodMotionFlare_P_RTP.bin"
    "*/firmware/159_fodMotionRipple_P_RTP.bin"
    "*/firmware/15_ringTone4_RTP.bin"
    "*/firmware/160_fodMotionSpiral_P_RTP.bin"
    "*/firmware/161_gameboxLaunch_P_RTP.bin"
    "*/firmware/162_GestureBackPull_P_RTP.bin"
    "*/firmware/163_GestureBackRelease_P_RTP.bin"
    "*/firmware/164_alert_P_RTP.bin"
    "*/firmware/165_feedbackNegativeLight_P_RTP.bin"
    "*/firmware/166_feedbackNeutral_P_RTP.bin"
    "*/firmware/167_feedbackPositive_P_RTP.bin"
    "*/firmware/168_fingerprintRecord_P_RTP.bin"
    "*/firmware/169_lockdown_P_RTP.bin"
    "*/firmware/16_ringTone4_RTP.bin"
    "*/firmware/170_slidingDamping_P_RTP.bin"
    "*/firmware/171_todoAlldone_P_RTP.bin"
    "*/firmware/172_uninstallAnimationIcon_P_RTP.bin"
    "*/firmware/173_signalButtonHighlight_P_RTP.bin"
    "*/firmware/174_signalButtonNegative_P_RTP.bin"
    "*/firmware/175_signalButton_P_RTP.bin"
    "*/firmware/176_signalClockHigh_P_RTP.bin"
    "*/firmware/177_signalClock_P_RTP.bin"
    "*/firmware/178_signalClockUnit_P_RTP.bin"
    "*/firmware/179_signalInputbox_P_RTP.bin"
    "*/firmware/17_ringTone4_RTP.bin"
    "*/firmware/180_signalKeyHigh_P_RTP.bin"
    "*/firmware/181_signalKeyUnit_P_RTP.bin"
    "*/firmware/182_signalListHighlight_P_RTP.bin"
    "*/firmware/183_signalList_P_RTP.bin"
    "*/firmware/184_signalPicker_P_RTP.bin"
    "*/firmware/185_signalPopup_P_RTP.bin"
    "*/firmware/186_signalSeekbar_P_RTP.bin"
    "*/firmware/187_signalSwitch_P_RTP.bin"
    "*/firmware/188_signalTab_P_RTP.bin"
    "*/firmware/189_signalText_P_RTP.bin"
    "*/firmware/18_ringTone4_RTP.bin"
    "*/firmware/190_signalTransitionLight_P_RTP.bin"
    "*/firmware/191_signalTransition_P_RTP.bin"
    "*/firmware/192_hapticsVideo_RTP.bin"
    "*/firmware/19_ringTone4_RTP.bin"
    "*/firmware/1_doubelClick_P_RTP.bin"
    "*/firmware/201_BoundaryBounce_RTP.bin"
    "*/firmware/202_BoundaryBottom_RTP.bin"
    "*/firmware/203_BoundaryTop_RTP.bin"
    "*/firmware/204_SlideTag_RTP.bin"
    "*/firmware/205_SuperPositive_RTP.bin"
    "*/firmware/206_Positive_RTP.bin"
    "*/firmware/207_Negative_RTP.bin"
    "*/firmware/208_Mute_RTP.bin"
    "*/firmware/209_ScreenLock_RTP.bin"
    "*/firmware/20_ringTone4_RTP.bin"
    "*/firmware/210_FingerprintUnlock_RTP.bin"
    "*/firmware/211_Charge_RTP.bin"
    "*/firmware/212_NotificationCleanup_RTP.bin"
    "*/firmware/213_ProcessCleanup_RTP.bin"
    "*/firmware/214_APPUninstallation_RTP.bin"
    "*/firmware/215_GameBoxStartup_RTP.bin"
    "*/firmware/216_EdittingMode_RTP.bin"
    "*/firmware/217_CameraShutter_RTP.bin"
    "*/firmware/23_Candy_P_RTP.bin"
    "*/firmware/24_Carousel_P_RTP.bin"
    "*/firmware/25_Celesta_P_RTP.bin"
    "*/firmware/26_Childhood_P_RTP.bin"
    "*/firmware/27_Country_P_RTP.bin"
    "*/firmware/28_Cowboy_P_RTP.bin"
    "*/firmware/2_tick_P_RTP.bin"
    "*/firmware/30_Fairyland_P_RTP.bin"
    "*/firmware/31_Fantasy_P_RTP.bin"
    "*/firmware/32_FieldTrip_P_RTP.bin"
    "*/firmware/33_Glee_P_RTP.bin"
    "*/firmware/35_IceLatte_P_RTP.bin"
    "*/firmware/36_KungFu_P_RTP.bin"
    "*/firmware/38_Lollipop_P_RTP.bin"
    "*/firmware/39_MiMix2_P_RTP.bin"
    "*/firmware/3_thud_P_RTP.bin"
    "*/firmware/40_Mi_P_RTP.bin"
    "*/firmware/41_MiHouse_P_RTP.bin"
    "*/firmware/42_MiJazz_P_RTP.bin"
    "*/firmware/43_MiRemix_P_RTP.bin"
    "*/firmware/44_MountainSpring_P_RTP.bin"
    "*/firmware/45_Orange_P_RTP.bin"
    "*/firmware/46_WindChime_P_RTP.bin"
    "*/firmware/47_SpaceAge_P_RTP.bin"
    "*/firmware/48_ToyRobot_P_RTP.bin"
    "*/firmware/49_Vigor_P_RTP.bin"
    "*/firmware/4_pop_P_RTP.bin"
    "*/firmware/50_Bottle_P_RTP.bin"
    "*/firmware/51_Bubble_P_RTP.bin"
    "*/firmware/521_AcousticGuitar_P_RTP.bin"
    "*/firmware/52_Bullfrog_P_RTP.bin"
    "*/firmware/53_Burst_P_RTP.bin"
    "*/firmware/54_Chirp_P_RTP.bin"
    "*/firmware/55_Clank_P_RTP.bin"
    "*/firmware/56_Crystal_P_RTP.bin"
    "*/firmware/57_FadeIn_P_RTP.bin"
    "*/firmware/58_FadeOut_P_RTP.bin"
    "*/firmware/59_Flute_P_RTP.bin"
    "*/firmware/5_heavyClick_P_RTP.bin"
    "*/firmware/60_Fresh_P_RTP.bin"
    "*/firmware/61_Frog_P_RTP.bin"
    "*/firmware/62_Guitar_P_RTP.bin"
    "*/firmware/63_Harp_P_RTP.bin"
    "*/firmware/64_IncomingMessage_P_RTP.bin"
    "*/firmware/65_MessageSent_P_RTP.bin"
    "*/firmware/66_Moment_P_RTP.bin"
    "*/firmware/67_NotificationXylophone_P_RTP.bin"
    "*/firmware/68_Potion_P_RTP.bin"
    "*/firmware/69_Radar_P_RTP.bin"
    "*/firmware/6_ringTone1_P_RTP.bin"
    "*/firmware/70_Spring_P_RTP.bin"
    "*/firmware/71_Swoosh_P_RTP.bin"
    "*/firmware/72_GestureUpSlide_P_RTP.bin"
    "*/firmware/73_fodMotionPlanet_P_RTP.bin"
    "*/firmware/74_ChargeWire_P_RTP.bin"
    "*/firmware/75_ChargeWireless_P_RTP.bin"
    "*/firmware/76_UnlockFailed_P_RTP.bin"
    "*/firmware/77_fodMotion1_P_RTP.bin"
    "*/firmware/78_fodMotion2_P_RTP.bin"
    "*/firmware/79_fodMotion3_P_RTP.bin"
    "*/firmware/7_ringTone2_P_RTP.bin"
    "*/firmware/80_fodMotion4_P_RTP.bin"
    "*/firmware/81_fodMotionAurora_P_RTP.bin"
    "*/firmware/82_FaceIDWrong2_P_RTP.bin"
    "*/firmware/83_uninstallAnimation_P_RTP.bin"
    "*/firmware/84_uninstallDialog_P_RTP.bin"
    "*/firmware/85_screenshot_P_RTP.bin"
    "*/firmware/86_lockscreenCameraEntry_P_RTP.bin"
    "*/firmware/87_launcherEdit_P_RTP.bin"
    "*/firmware/88_launcherIconSelection_P_RTP.bin"
    "*/firmware/8_ringTone3_P_RTP.bin"
    "*/firmware/90_taskCleanAll_P_RTP.bin"
    "*/firmware/91_newIconFolder_P_RTP.bin"
    "*/firmware/92_notificationRemove_P_RTP.bin"
    "*/firmware/93_notificationCleanall_P_RTP.bin"
    "*/firmware/96_nfcCard_P_RTP.bin"
    "*/firmware/98_nfcCardSlow_P_RTP.bin"
    "*/firmware/99_POCO_P_RTP.bin"
    "*/firmware/9_ringTone4_P_RTP.bin"
    "*/lib64/android.hardware.vibrator-V1-ndk_platform.so"
    "*/lib64/hw/vibrator.default.so"
    "*/lib64/libvibrator.so"
    "*/lib64/vendor.hardware.vibratorfeature.IVibratorExt-V1-ndk_platform.so"
    "*/lib/hw/vibrator.default.so"
    "*/lib/libvibrator.so"

    # VINTF manifests and fragments
    "*/etc/vintf/compatibility_matrix.xml"
    "*/etc/vintf/manifest_fuxi.xml"
    "*/etc/vintf/manifest_ishtar.xml"
    "*/etc/vintf/manifest_kalama.xml"
    "*/etc/vintf/manifest_nuwa.xml"
    "*/etc/vintf/manifest_sheng.xml"
    "*/etc/vintf/manifest_socrates.xml"
    "*/etc/vintf/manifest_vermeer.xml"
    "*/etc/vintf/manifest_wangshu.xml"

    # WiFi
    "*/bin/hostapd_cli"
    "*/bin/hw/android.hardware.wifi@1.0-service"
    "*/bin/hw/hostapd"
    "*/bin/hw/wpa_supplicant"
    "*/bin/wpa_cli"
    "*/etc/init/android.hardware.wifi@1.0-service.rc"
    "*/etc/init/android.hardware.wifi.supplicant-service.rc"
    "*/etc/init/hostapd.android.rc"
    "*/etc/vintf/manifest/android.hardware.wifi@1.0-service.xml"
    "*/etc/vintf/manifest/android.hardware.wifi.hostapd.xml"
    "*/etc/vintf/manifest/android.hardware.wifi.supplicant.xml"
    "*/etc/wifi/wpa_supplicant.conf"
    "*/lib64/android.hardware.wifi@1.0.so"
    "*/lib64/android.hardware.wifi@1.1.so"
    "*/lib64/android.hardware.wifi@1.2.so"
    "*/lib64/android.hardware.wifi@1.3.so"
    "*/lib64/android.hardware.wifi@1.4.so"
    "*/lib64/android.hardware.wifi@1.5.so"
    "*/lib64/android.hardware.wifi@1.6.so"
    "*/lib64/android.hardware.wifi.supplicant@1.0.so"
    "*/lib64/android.system.wifi.keystore@1.0.so"
    "*/lib64/libcld80211.so"
    "*/lib64/libkeystore-engine-wifi-hidl.so"
    "*/lib64/libkeystore-wifi-hidl.so"
    "*/lib64/libwifi-hal-ctrl.so"
    "*/lib64/libwifi-hal-qcom.so"
    "*/lib64/libwifi-hal.so"
    "*/lib64/libwpa_client.so"
    "*/lib64/vendor.qti.hardware.wifi.supplicant-V1-ndk.so"
    "*/lib/libcld80211.so"
    "*/lib/libwifi-hal-ctrl.so"
    "*/lib/libwifi-hal-qcom.so"
    "*/lib/libwpa_client.so"

    # Xiaomi services
    "*/bin/hw/vendor.xiaomi.cit.bluetooth@1.0-service"
    "*/bin/hw/vendor.xiaomi.cit.wifi@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.blackbox.service"
    "*/bin/hw/vendor.xiaomi.hardware.cld@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.dtool@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.fbo@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.keyboardnanoapp@1.0-client"
    "*/bin/hw/vendor.xiaomi.hardware.keyboardnanoapp@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.micharge@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.mimd@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.miperf@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.misight.service"
    "*/bin/hw/vendor.xiaomi.hardware.misys@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.misys@2.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.misys@3.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.misys@4.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.quickcamera@1.0-service"
    "*/bin/hw/vendor.xiaomi.hardware.swap@1.0-service"
    "*/bin/hw/vendor.xiaomi.hidl.minet@1.0-service"
    "*/bin/hw/vendor.xiaomi.hidl.miwill@1.0-service"
    "*/bin/hw/vendor.xiaomi.sensor.citsensorservice@2.0-service"
    "*/bin/hw/vendor.xiaomi.sensor.communicate@1.0-service"
    "*/bin/minetd"
    "*/etc/init/blackbox.rc"
    "*/etc/init/mi-misight.rc"
    "*/etc/init/vendor.xiaomi.cit.bluetooth@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.cit.wifi@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.cld@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.dtool@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.fbo@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.keyboardnanoapp@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.micharge@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.mimd@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.miperf@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.misys@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.misys@2.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.misys@3.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.misys@4.0-service.rc"
    "*/etc/init/vendor.xiaomi.hardware.swap@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hidl.minet@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.hidl.miwill@1.0-service.rc"
    "*/etc/init/vendor.xiaomi.sensor.citsensorservice@2.0-service.rc"
    "*/etc/init/vendor.xiaomi.sensor.communicate@1.0-service.rc"
    "*/etc/init/minetd.rc"
    "*/etc/vintf/manifest/blackbox.xml"
    "*/etc/vintf/manifest/manifest_vendor.xiaomi.hardware.cld.xml"
    "*/etc/vintf/manifest/manifest_vendor.xiaomi.hardware.fbo.xml"
    "*/etc/vintf/manifest/manifest_vendor.xiaomi.hardware.swap.xml"
    "*/etc/vintf/manifest/mi-misight.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.cit.bluetooth@1.0_manifest.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.cit.wifi@1.0_manifest.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.keyboardnanoapp@1.0_manifest.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.micharge@1.0.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.mimd@1.0-service.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.miperf@1.0.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.misys@1.0.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.misys@2.0.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.misys@3.0.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.misys@4.0.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.hardware.quickcamera@1.0-service.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.sensor.citsensorservice@2.0-service.xml"
    "*/etc/vintf/manifest/vendor.xiaomi.sensor.communicate@1.0_manifest.xml"
    "*/lib64/hw/vendor.xiaomi.hardware.cld@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.fbo@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.micharge@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.miperf@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.misys@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.misys@2.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.misys@3.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.misys@4.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.quickcamera@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.hardware.swap@1.0-impl.so"
    "*/lib64/hw/vendor.xiaomi.sensor.citsensorservice@2.0-impl.so"
    "*/lib64/vendor.xiaomi.cit.bluetooth@1.0.so"
    "*/lib64/vendor.xiaomi.cit.wifi@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.cld@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.dtool@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.fbo@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.keyboardnanoapp@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.micharge@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.mimd@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.miperf@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.misight-V1-ndk_platform.so"
    "*/lib64/vendor.xiaomi.hardware.misys@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.misys@2.0.so"
    "*/lib64/vendor.xiaomi.hardware.misys@3.0.so"
    "*/lib64/vendor.xiaomi.hardware.misys@4.0.so"
    "*/lib64/vendor.xiaomi.hardware.quickcamera@1.0.so"
    "*/lib64/vendor.xiaomi.hardware.swap@1.0.so"
    "*/lib64/vendor.xiaomi.hidl.minet@1.0-impl.so"
    "*/lib64/vendor.xiaomi.hidl.minet@1.0.so"
    "*/lib64/vendor.xiaomi.hidl.miwill@1.0-impl.so"
    "*/lib64/vendor.xiaomi.hidl.miwill@1.0.so"
    "*/lib64/vendor.xiaomi.sensor.communicate@1.0.so"
    "*/lib/hw/vendor.xiaomi.hardware.cld@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.fbo@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.micharge@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.miperf@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.misys@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.misys@2.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.misys@3.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.misys@4.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.quickcamera@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.hardware.swap@1.0-impl.so"
    "*/lib/hw/vendor.xiaomi.sensor.citsensorservice@2.0-impl.so"
    "*/lib/vendor.xiaomi.hardware.cld@1.0.so"
    "*/lib/vendor.xiaomi.hardware.fbo@1.0.so"
    "*/lib/vendor.xiaomi.hardware.micharge@1.0.so"
    "*/lib/vendor.xiaomi.hardware.miperf@1.0.so"
    "*/lib/vendor.xiaomi.hardware.misys@1.0.so"
    "*/lib/vendor.xiaomi.hardware.misys@2.0.so"
    "*/lib/vendor.xiaomi.hardware.misys@3.0.so"
    "*/lib/vendor.xiaomi.hardware.misys@4.0.so"
    "*/lib/vendor.xiaomi.hardware.quickcamera@1.0.so"
    "*/lib/vendor.xiaomi.hardware.swap@1.0.so"
    "*/lib/vendor.xiaomi.hidl.minet@1.0-impl.so"
    "*/lib/vendor.xiaomi.hidl.minet@1.0.so"
    "*/lib/vendor.xiaomi.hidl.miwill@1.0-impl.so"
    "*/lib/vendor.xiaomi.hidl.miwill@1.0.so"
)

declare -A VENDOR_MODULE_DEST

VENDOR_MODULE_DEST=(
    ["odm/firmware/0_click_P_RTP.bin"]="vendor/etc/vibrator/effect_0.bin"
    ["odm/firmware/1_doubelClick_P_RTP.bin"]="vendor/etc/vibrator/effect_1.bin"
    ["odm/firmware/2_tick_P_RTP.bin"]="vendor/etc/vibrator/effect_2.bin"
    ["odm/firmware/3_thud_P_RTP.bin"]="vendor/etc/vibrator/effect_3.bin"
    ["odm/firmware/4_pop_P_RTP.bin"]="vendor/etc/vibrator/effect_4.bin"
    ["odm/firmware/5_heavyClick_P_RTP.bin"]="vendor/etc/vibrator/effect_5.bin"
)

VENDOR_MODULE_FILES=(
    "*.apk"
    "libaudio_log_utils.so"
    "libar-pal.so"
    "libagm.so"
    "vendor.qti.hardware.AGMIPC@1.0-impl.so"
    "vendor.qti.hardware.pal@1.0-impl.so"
)

VENDOR_SKIP_LINKS=(
    "*/bin/*"
    "*/odm"
    "*/lib/modules"
)

function check_array_regex() {
  local string_to_check=$1
  local array=("${@:2}")

  for pattern in "${array[@]}"; do
    if [[ $string_to_check == $pattern ]] || [[ $string_to_check =~ $pattern ]]; then
      return 0
    fi
  done

  return 1
}

function usage() {
    echo "Usage: $(basename $0) <path-to-vendor-and-odm>"
    exit 1
}

function write_prop_file() {
    if [[ -z $2 ]]; then
        echo $1 >> $VENDOR_PROP_FILE
    else
        echo $1:$2 >> $VENDOR_PROP_FILE
    fi
}

if [[ -z $VENDOR_ODM_PATH ]] || [[ ! -d $VENDOR_ODM_PATH ]]; then
    usage
fi

for dir in odm vendor; do
    if [[ ! -d $VENDOR_ODM_PATH/$dir ]]; then
        echo "Missing $VENDOR_ODM_PATH/$dir"
        usage
    fi
done


rm -f $VENDOR_PROP_FILE
FULL_FILES_LIST=$(cd $VENDOR_ODM_PATH && find odm vendor -type f | sort)
for file in $FULL_FILES_LIST; do
    SKIP=false
    MODULE=false
    destination=${VENDOR_MODULE_DEST[$file]}

    check_array_regex "$file" "${VENDOR_SKIP_FILES[@]}" && SKIP=true
    check_array_regex "$file" "${VENDOR_MODULE_FILES[@]}" && MODULE=true

    if [[ $SKIP == true ]] && [[ "$destination" == "" ]]; then
        echo "--- Skipping: $file"
    elif [[ $MODULE == true ]]; then
        echo "--- Adding as module: $file"
        write_prop_file "-$file" "$destination"
    else
        echo "--- Adding as copy: $file"
        write_prop_file "$file" "$destination"
    fi
done

rm -f $VENDOR_SYMLINKS_MK
FULL_LINK_LIST=$(cd $VENDOR_ODM_PATH/vendor && find * -type l | sort)
for link in $FULL_LINK_LIST; do
    SKIP=false
    link_target=$(readlink $VENDOR_ODM_PATH/vendor/$link)

    check_array_regex "vendor/$link" "${VENDOR_SKIP_LINKS[@]}" && SKIP=true

    if [[ $SKIP == true ]]; then
        echo "--- Skipping: $link"
    else
        echo "--- Adding as symlink: vendor/$link -> $link_target"
        echo "\$(TARGET_OUT_VENDOR)/$link: \$(LOCAL_INSTALLED_MODULE)" >> $VENDOR_SYMLINKS_MK
        echo "\$(call symlink-file,,$link_target,\$(TARGET_OUT_VENDOR)/$link)" >> $VENDOR_SYMLINKS_MK
        echo "ALL_DEFAULT_INSTALLED_MODULES += \$(TARGET_OUT_VENDOR)/$link" >> $VENDOR_SYMLINKS_MK
    fi
done
